[package]
name = "layout-config"
version = "0.1.0"
edition = "2021"

[lib]
name = "layout_config"
path = "src/lib.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
