[package]
name = "user-config"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1"
serde = { version = "1", features = ["derive"] }
layout = { path = "../layout/" }
layout-config = { path = "../layout-config/" }
tui = "*"
